---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.
```{r}
library(tidyverse)
library(janitor)
```

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
heartrate <- read_csv("data/heartrate.csv")
```
```{r}
glimpse(heartrate)
```


1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate %>% 
  ggplot(aes(x = patient, y = a)) +
  geom_col() +
  labs(title = "Heartate of Patients for Drug A", y = "Heartrate")
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate_tidy <- heartrate %>% 
  pivot_longer(cols = -"patient", names_to = "drug", values_to = "heartrate")
heartrate_tidy
```

```{r}
heartrate_tidy %>% 
  ggplot(aes(x = drug, y = heartrate, fill = drug)) +
  geom_boxplot()
```

